name: a015_fresh_basket
description: A new Flutter project.

publish_to: 'Digikull'
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Responsiveness
  flutter_screenutil: ^5.5.3+2

  # Firebase Dependencies
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  firebase_auth: ^3.6.2
  firebase_storage: ^10.2.18
  http: ^0.13.4
  firebase_auth_platform_interface: ^6.5.2


  # Other Dependencies
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.2
  provider: ^6.0.3
  flutter_iconly: ^1.0.2
  card_swiper: ^2.0.1
  fancy_shimmer_image: ^2.0.2
  flutter_staggered_grid_view: ^0.6.1
  badges: ^2.0.3


  # URL Launcher
  url_launcher: ^6.1.5


  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/appbar/
    - assets/categories/
    - assets/darkMode/
    - assets/images/
    - assets/logo/
    - assets/offers/